steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/monerod-pruned-ready', '.' ]
timeout: 86400s
tags: ['latest', 'monero-0.17.1.8']
images: ['gcr.io/$PROJECT_ID/monerod-pruned-ready']
